DROP TYPE IF EXISTS grocery;
Create type grocery as ENUM (
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
);

DROP TABLE IF EXISTS shopping_list;

CREATE TABLE shopping_list (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  price DEC(8, 2) NOT NULL,
  date_added timestamp DEFAULT NOW(),
  checked BOOLEAN DEFAULT FALSE,
  category grocery NOT NULL
);